# 프로즌레이크 소개

- S에서 출발하여 G까지 도달하는 것이 목표
- H를 밟으면 실패
- 취할 수 있는 액션은 UP, DOWN, RIGHT, LEFT
- `is_slippery`가 True라면 일정 확률로 입력을 무시하고 랜덤 액션을 취한다.

# 예제 소개

- 예제에서 사용되는 맵은 4x4 크기로서 총 16개의 상태가 있다.
- 각 상태에서 수행할 수 있는 액션은 총 4개
- 따라서 16 * 4의 Dimension으로 학습이 진행된다.

In [1]:
import gym
from gym.envs.registration import register
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
register(
    id='FrozenLake-v3', 
    entry_point='gym.envs.toy_text:FrozenLakeEnv', 
    kwargs={'map_name':'4x4', 'is_slippery':True}
)

env = gym.make('FrozenLake-v3')

In [3]:
# 테이블을 모두 0으로 초기화한다.
Q = np.zeros([env.observation_space.n, env.action_space.n])

# 학습 매개변수를 설정한다.
lr = .85
y = .99
num_episodes = 2000

# 보상의 총계를 담을 리스트를 생성한다.
rList = []

In [4]:
for i in range(num_episodes):
    # 환경을 리셋하고 첫번째 새로운 관찰을 얻는다.
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    
    # Q 테이블 학습 알고리즘
    while j < 99:
        j += 1
        # Q 테이블로부터의 (노이즈와 함께) 그리디하게 액션을 선택
        a = np.argmax(Q[s,:] + np.random.randn(1, env.action_space.n) * (1. / (i + 1)))
        # 환경으로부터 새로운 상태와 보상을 얻는다.
        s1, r, d, _ = env.step(a)
        # 새로운 지식을 통해 Q 테이블을 업데이트한다.
        Q[s, a] = Q[s, a] + lr * (r + y * np.max(Q[s1, :]) - Q[s, a])
        rAll += r
        s = s1
        
        if d == True:
            print(str(i), " episode reward = ", r)
            break
                      
rList.append(rAll)

s = env.reset()
stepIndex = 0
while True:    
    stepIndex += 1
    action = np.argmax(Q[s, :] + np.random.randn(1, env.action_space.n))
    state, reward, done, info = env.step(action)
    print("##### " + str(stepIndex) + " #####")
    env.render()
    if done == True:
        print("Finished with reward: ", reward)
        break;
    

0  episode reward =  0.0
1  episode reward =  0.0
2  episode reward =  0.0
3  episode reward =  0.0
4  episode reward =  0.0
5  episode reward =  0.0
6  episode reward =  0.0
7  episode reward =  0.0
8  episode reward =  0.0
9  episode reward =  0.0
10  episode reward =  0.0
11  episode reward =  0.0
12  episode reward =  0.0
13  episode reward =  0.0
14  episode reward =  0.0
15  episode reward =  0.0
16  episode reward =  0.0
17  episode reward =  0.0
18  episode reward =  0.0
19  episode reward =  0.0
20  episode reward =  0.0
21  episode reward =  0.0
22  episode reward =  0.0
23  episode reward =  0.0
24  episode reward =  0.0
25  episode reward =  0.0
26  episode reward =  0.0
27  episode reward =  0.0
28  episode reward =  0.0
29  episode reward =  0.0
30  episode reward =  0.0
31  episode reward =  0.0
32  episode reward =  0.0
33  episode reward =  0.0
34  episode reward =  0.0
35  episode reward =  0.0
36  episode reward =  0.0
37  episode reward =  1.0
38  episode reward =  

348  episode reward =  1.0
349  episode reward =  0.0
350  episode reward =  0.0
351  episode reward =  0.0
352  episode reward =  1.0
353  episode reward =  1.0
354  episode reward =  0.0
355  episode reward =  0.0
356  episode reward =  1.0
357  episode reward =  0.0
358  episode reward =  0.0
359  episode reward =  0.0
361  episode reward =  1.0
362  episode reward =  1.0
363  episode reward =  0.0
364  episode reward =  1.0
365  episode reward =  1.0
366  episode reward =  0.0
368  episode reward =  1.0
369  episode reward =  1.0
370  episode reward =  0.0
371  episode reward =  1.0
373  episode reward =  1.0
374  episode reward =  1.0
375  episode reward =  0.0
377  episode reward =  1.0
379  episode reward =  0.0
380  episode reward =  1.0
384  episode reward =  1.0
385  episode reward =  0.0
386  episode reward =  1.0
387  episode reward =  0.0
388  episode reward =  1.0
389  episode reward =  1.0
390  episode reward =  1.0
391  episode reward =  1.0
392  episode reward =  1.0
3

721  episode reward =  0.0
722  episode reward =  0.0
723  episode reward =  1.0
724  episode reward =  1.0
725  episode reward =  1.0
726  episode reward =  1.0
727  episode reward =  1.0
728  episode reward =  0.0
729  episode reward =  0.0
730  episode reward =  0.0
731  episode reward =  1.0
732  episode reward =  1.0
733  episode reward =  0.0
734  episode reward =  1.0
735  episode reward =  1.0
736  episode reward =  0.0
738  episode reward =  1.0
739  episode reward =  1.0
740  episode reward =  1.0
741  episode reward =  1.0
742  episode reward =  1.0
743  episode reward =  1.0
744  episode reward =  1.0
745  episode reward =  0.0
746  episode reward =  1.0
747  episode reward =  0.0
748  episode reward =  1.0
749  episode reward =  1.0
750  episode reward =  0.0
751  episode reward =  1.0
752  episode reward =  1.0
753  episode reward =  1.0
754  episode reward =  0.0
755  episode reward =  0.0
756  episode reward =  1.0
757  episode reward =  1.0
758  episode reward =  1.0
7

1098  episode reward =  0.0
1099  episode reward =  1.0
1100  episode reward =  1.0
1101  episode reward =  0.0
1103  episode reward =  1.0
1104  episode reward =  0.0
1105  episode reward =  1.0
1106  episode reward =  0.0
1107  episode reward =  0.0
1108  episode reward =  0.0
1109  episode reward =  1.0
1112  episode reward =  1.0
1115  episode reward =  0.0
1116  episode reward =  1.0
1117  episode reward =  1.0
1118  episode reward =  1.0
1119  episode reward =  1.0
1120  episode reward =  1.0
1121  episode reward =  1.0
1122  episode reward =  1.0
1123  episode reward =  1.0
1124  episode reward =  1.0
1125  episode reward =  1.0
1126  episode reward =  0.0
1127  episode reward =  1.0
1128  episode reward =  1.0
1129  episode reward =  1.0
1130  episode reward =  1.0
1131  episode reward =  0.0
1132  episode reward =  1.0
1133  episode reward =  1.0
1134  episode reward =  1.0
1137  episode reward =  1.0
1139  episode reward =  1.0
1140  episode reward =  1.0
1141  episode reward

1481  episode reward =  1.0
1482  episode reward =  1.0
1483  episode reward =  0.0
1484  episode reward =  1.0
1485  episode reward =  1.0
1486  episode reward =  1.0
1487  episode reward =  0.0
1488  episode reward =  1.0
1489  episode reward =  1.0
1490  episode reward =  0.0
1492  episode reward =  0.0
1493  episode reward =  0.0
1494  episode reward =  1.0
1496  episode reward =  1.0
1497  episode reward =  0.0
1498  episode reward =  0.0
1499  episode reward =  0.0
1500  episode reward =  1.0
1501  episode reward =  0.0
1502  episode reward =  1.0
1503  episode reward =  1.0
1505  episode reward =  1.0
1506  episode reward =  1.0
1507  episode reward =  1.0
1508  episode reward =  1.0
1509  episode reward =  1.0
1510  episode reward =  1.0
1511  episode reward =  0.0
1512  episode reward =  1.0
1513  episode reward =  0.0
1514  episode reward =  1.0
1515  episode reward =  1.0
1516  episode reward =  1.0
1517  episode reward =  1.0
1518  episode reward =  0.0
1520  episode reward

1853  episode reward =  1.0
1854  episode reward =  1.0
1855  episode reward =  1.0
1856  episode reward =  0.0
1857  episode reward =  0.0
1858  episode reward =  1.0
1859  episode reward =  1.0
1860  episode reward =  1.0
1861  episode reward =  1.0
1862  episode reward =  1.0
1863  episode reward =  1.0
1866  episode reward =  0.0
1868  episode reward =  1.0
1870  episode reward =  1.0
1871  episode reward =  1.0
1872  episode reward =  1.0
1874  episode reward =  0.0
1876  episode reward =  1.0
1877  episode reward =  0.0
1878  episode reward =  1.0
1880  episode reward =  0.0
1881  episode reward =  1.0
1883  episode reward =  0.0
1884  episode reward =  1.0
1885  episode reward =  0.0
1886  episode reward =  1.0
1887  episode reward =  1.0
1888  episode reward =  0.0
1889  episode reward =  0.0
1890  episode reward =  0.0
1891  episode reward =  0.0
1892  episode reward =  0.0
1894  episode reward =  1.0
1895  episode reward =  1.0
1896  episode reward =  1.0
1898  episode reward

In [5]:
print("Score over time: " + str(sum(rList) / num_episodes))

Score over time: 0.0005


In [6]:
print("Final Q-Table Values ")
print(Q)

Final Q-Table Values 
[[4.25135859e-01 1.60809485e-02 1.38649774e-02 2.41362440e-02]
 [1.72286467e-03 3.19136781e-04 2.09345300e-03 4.20134699e-01]
 [1.15864336e-02 2.32328638e-02 4.99588034e-03 5.18110420e-01]
 [1.91026303e-04 1.28301882e-03 7.81865500e-04 3.96494932e-01]
 [4.92380821e-01 5.34070380e-04 4.91005902e-03 1.70254591e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.18983276e-04 1.45912352e-04 4.40493145e-01 9.63752149e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.38454991e-03 4.52691373e-03 4.89003012e-03 2.50098362e-01]
 [0.00000000e+00 6.82326448e-01 0.00000000e+00 1.60425518e-03]
 [1.18045268e-01 3.48557780e-04 1.10429111e-04 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.07841416e-01 8.39908487e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.19127854e-01]
 [0.00000000e+00 0.00000000e+00 0